export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const CHECK_USER_SESSION = 'CHECK_USER_SESSION';

export const SIGNUP_START = 'SIGNUP_START';
export const SINGUP_SUCCESS = 'SINGUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const GOOGLE_SIGNIN_START = 'GOOGLE_SIGNIN_START';
export const EMAIL_SIGNIN_START = 'EMAIL_SIGNIN_START';
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS';
export const SIGNIN_FAILURE = 'SIGNIN_FAILURE';

export const SIGNOUT_START = 'SIGNOUT_START';
export const SINGOUT_SUCCESS = 'SINGOUT_SUCCESS';
export const SIGNOUT_FAILURE = 'SIGNOUT_FAILURE';

export const ADD_ITEM = 'ADD_ITEM';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const TOGGLE_CART_HIDDEN = 'TOGGLE_CART_HIDDEN';
export const CLEAR_ITEM_FROM_CART = 'CLEAR_ITEM_FROM_CART';
export const CLEAR_CART = 'CLEAR_CART';

export const FETCH_COLLECTIONS_FAILURE = 'FETCH_COLLECTIONS_FAILURE';
export const FETCH_COLLECTIONS_START = 'FETCH_COLLECTIONS_START';
export const FETCH_COLLECTIONS_SUCCESS = 'FETCH_COLLECTIONS_SUCCESS';

export const UPDATE_COLLECTIONS = 'UPDATE_COLLECTIONS';
