export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const GOOGLE_SIGNIN_START = 'GOOGLE_SIGNIN_START';
export const GOOGLE_SIGNIN_SUCCESS = 'GOOGLE_SIGNIN_SUCCESS';
export const GOOGLE_SIGNIN_FAILURE = 'GOOGLE_SIGNIN_FAILURE';

export const EMAIL_SIGNIN_START = 'EMAIL_SIGNIN_START';
export const EMAIL_SIGNIN_SUCCESS = 'EMAIL_SIGNIN_SUCCESS';
export const EMAIL_SIGNIN_FAILURE = 'EMAIL_SIGNIN_FAILURE';

export const ADD_ITEM = 'ADD_ITEM';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const TOGGLE_CART_HIDDEN = 'TOGGLE_CART_HIDDEN';
export const CLEAR_ITEM_FROM_CART = 'CLEAR_ITEM_FROM_CART';

export const FETCH_COLLECTIONS_FAILURE = 'FETCH_COLLECTIONS_FAILURE';
export const FETCH_COLLECTIONS_START = 'FETCH_COLLECTIONS_START';
export const FETCH_COLLECTIONS_SUCCESS = 'FETCH_COLLECTIONS_SUCCESS';

export const UPDATE_COLLECTIONS = 'UPDATE_COLLECTIONS';
